version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data